[profile.default]
solc = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@src/=src/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[fmt]
line_length = 200
